### ISSUE TITLE
탐색개발

### ISSUE THREAD

**Issue by soulee-dev** [soulee-dev/webserv#1]
HTTP, CGI 등 새로 배우는 개념들에 대해 학습하는 기간입니다.
모르는 개념들에 대해 자주적으로 학습을 진행합니다.
궁금한 사항들은 서로 질문하며, 동료 학습을 진행합니다.

**Comment by soulee-dev** [comment]
궁금한 내용들에 대해서 이 Issue에 적어주세요.

**Comment by soulee-dev** [comment]
긴 호흡으로 프로젝트가 진행되는 만큼, Commit convention과 Coding convention이 필요하단 생각이 듭니다.
관련 자료에 대해 찾아 보고, 도입에 대해 다시 이야기 드리겠습니다.

**Comment by soulee-dev** [comment]
학습이 필요한 부분:
- HTTP
- 소켓 통신
- 멀티플렉싱 (Multiplexing)

**Comment by soulee-dev** [comment]
5일차

**Comment by soulee-dev** [comment]
@soulee-dev
5일차 학습 내용
- Computer System A Pogrammer's Perspective 참고 Mini Webserver 구현
- Socker Echo Server 구현

**Comment by Espebaum** [comment]
@Espebaum 

 * Http 에러 코드, 구글이 지원하는 에러코드
 * NGINX Configure file 구조 파악

**Comment by soulee-dev** [comment]
6일차는 팀원들의 개인 일정으로 인해 쉬어갑니다.
