### ISSUE TITLE
[파싱 에러] max_body_size는 location별로 들고 있어야 함

### ISSUE THREAD

**Issue by soulee-dev** [soulee-dev/webserv#105]
현재는 서버 블럭에서만 파싱이 되는것 같음. 로케이션별로 들고 있어야 함

**Comment by CodyKat** [comment]
추가해보겠습니다

**Comment by CodyKat** [comment]
헤더 확인해보니 location별로도 지정이 가능해 보이는데 값이 안가져와지나요?

**Comment by soulee-dev** [comment]
@CodyKat 잘 되는것 확인 했습니다. getter를 잘 확인 안한 제 불찰입니다
