### ISSUE TITLE
is_put false 로 초기화 한 후 제대로 값 넣어주는 곳이 없음 

### ISSUE THREAD

**Issue by bestjinam** [soulee-dev/webserv#157]
https://github.com/soulee-dev/webserv/blob/172722fb3276cbb0d80266f8b4da5c9e8b74a74b/srcs/Message/Request.cpp#L22

**Comment by CodyKat** [comment]
확인해보고 필요없으면 지우겠습니다

**Comment by CodyKat** [comment]
is_put을 지우고 request.method를 확인하는 것으로 수정했습니다
