### ISSUE TITLE
default.conf가 있는 경우 자동적으로 conf 불러오기

### ISSUE THREAD

**Issue by soulee-dev** [soulee-dev/webserv#39]

**Comment by bestjinam** [comment]
이거는 매개변수를 넣지 않았을때를 말하는거죠? 

webserv 뒤에 파일 이름을 넣지 않았는데, 
해당 경로에 default.conf 가 있으면, 그걸 읽어서 올리고, 
없다면 에러처리 ?

**Comment by soulee-dev** [comment]
@bestjinam 네 맞아요 해당 경로에 default.conf가 있으면 읽어서 run하고 그것 마저 없으면 error.
