### ISSUE TITLE
cgi-bin path를 설정파일로 부터 가져올 수 있게 하기

### ISSUE THREAD

**Issue by CodyKat** [soulee-dev/webserv#75]
## 문제상황
테스터기는 폴더와 파일에다가 POST, PUT을 시도한다. 이경우 파일을 열어 body에 담긴 정보를 파일에 넣고 그 내용을 다시 응답으로 보내줘야한다.
하지만 우리는 URI에 cgi-bin이 들어간 경우에만 cgi를 실행하고 나머지의 경우 static으로 처리한다.

## 대안
cgi경로인 cgi PATH를 설정파일에서 설정할 수 있도록 하면 테스터기를 통과하지 않더라도 디펜스가 가능 할 것이라 생각함

**Comment by bestjinam** [comment]
@CodyKat POST, PUT을 Stream으로 구현 함으로써, Issue Close.
