### ISSUE TITLE
이상한 Method 들어왔을 때 적당한 처리 필요합니다.

### ISSUE THREAD

**Issue by Espebaum** [soulee-dev/webserv#85]
https://github.com/soulee-dev/webserv/blob/a033584707e722c5b7dceabc86b7004bceb803e1/srcs/Http/Handler/Handler.cpp#L154

메소드 빈거 들어오면 404띄우게 했는데 allowed method 대조해서 에러 띄워야할것같습니다.

**Comment by CodyKat** [comment]
#87 브랜치에서 allow method 인지 체크하는 로직을 추가하였습니다. (checkMethod 함수 추가)

**Comment by CodyKat** [comment]
#99 을 통해 마지함
