### ISSUE TITLE
bool Client::readEventProcess(void)에서 getRequest하는데 로직 오류가 있어요

### ISSUE THREAD

**Issue by Espebaum** [soulee-dev/webserv#90]
https://github.com/soulee-dev/webserv/blob/45b0b79e0a2f7ee5047b479c317f2c6fb376a681/srcs/Client.cpp#L82

Request를 파싱할 때는 getBackReq()로 파싱하는데, 파싱된걸로 정적/동적 등 처리할때는 getFrontReq()로 합니다. 근데 지금 Pop이 제대로 안되서 getBackReq()과 getFrontReq()가 서로 다른 걸 가리켜서 Error Code가 앞뒷열이 달라서 오류가 발생합니다. Pop할 지점을 찾아야합니다.

**Comment by CodyKat** [comment]
찾아보겠습니다!

**Comment by bestjinam** [comment]
이거 일단 팝 하는 로직 오기 전까지는 큐 맨뒤에 있는 리퀘스트 쓰도록 해서 고쳐 두긴 했는데, 여전히 문제가 있긴 함. 

왜냐하면 충분히 그 다음 리퀘스트가 들어와서 뒤에 새 리퀘스트가 붙을수있는 위험에 노출되는지점이 있기 때문임.

**Comment by soulee-dev** [comment]
현재 수정중임 최신 Issue에서 확인 바람.
