### ISSUE TITLE
POST 1억 바이트 존재하지 않는 cgi path에 보내는 경우

### ISSUE THREAD

**Issue by soulee-dev** [soulee-dev/webserv#91]
```bash
Test POST http://localhost:80/directory/youpla.bla with a size of 100000000
FATAL ERROR ON LAST TEST: bad status code
```

**Comment by soulee-dev** [comment]
저 경로에 파일을 만들어 주면 200으로 바뀜, 하지만
데이터를 보내주다가 EV ERROR로 바뀌면서 죽음

**Comment by soulee-dev** [comment]
랜덤성을 갖고 있는지 모르겠지만...
```bash
FATAL ERROR ON LAST TEST: bad cgi returned size body
```
로 에러 메시지가 바뀜

**Comment by soulee-dev** [comment]
curl을 이용해서 데이터를 보내면 처음에는 보내져서 반환이 잘 오는데
이후에는
```
curl: (52) Empty reply from server
```
라고 나옴

보낸 명령어
```
curl -v -X POST -d "aaaaaaa" http://localhost:80/directory/youpi.bla
```
그리고 ident의 숫자가 증가함. fd leak이 발생 할수도 있음
EV_ERROR가 발생하는 경우 ident 0이 disconnect됨 왜 인지 모르겠음.

**Comment by soulee-dev** [comment]
서버에서 클라이언트로 보낼때 body 사이즈를 찍어봤는데
크기가 0으로 나옴.

**Comment by CodyKat** [comment]
Dynamic이 아닌 Static handler로 들어가고 있는것을 확인함
원인은 파싱에서 request.method가 "\r\nPOST"로 들어가고 있던것이 원인이었음

**Comment by soulee-dev** [comment]
#96 에서 해결 됨
