### ISSUE TITLE
x-secret-header-for-test 테스트

### ISSUE THREAD

**Issue by CodyKat** [soulee-dev/webserv#93]
헤더에 x-secret-header-for-test : 1가 추가되어 들어오는 POST 테스트에서 막힘

Test POST http://localhost:80/directory/youpi.bla with a size of 100000 with special headers

테스트 request 헤더 전문
```
accept-encoding : gzip
content-type : test/file
host : localhost:80
transfer-encoding : chunked
user-agent : Go-http-client/1.1
x-secret-header-for-test : 1
```

결과 : FATAL ERROR ON LAST TEST: bad cgi returned size body

**Comment by bestjinam** [comment]
슬랙을 보니 이렇게 나오는데 cgi 보낼때 env 로 같이 보내줘야 한다는걸까요? 
TTP_X_SECRET_HEADER_FOR_TEST should be the env var

**Comment by CodyKat** [comment]
네

**Comment by Espebaum** [comment]
bool Client::readMessage(void) <- 여기 read에서 에러나고 ERRNO는 54 Connection reset by peer네요. Clientfd로부터 읽던데 이거는 cgi에서 제대로 데이터를 안써줘서 그런거겟죠?

**Comment by Espebaum** [comment]
<img width="1535" alt="Screen Shot 2023-08-17 at 5 20 47 PM" src="https://github.com/soulee-dev/webserv/assets/104741009/7c93fe4d-7245-4531-87f8-3c6cf06971ba">
일단 이대로 써넣어줫는데

**Comment by CodyKat** [comment]
TTP가 아니라 HTTP일겁니다

**Comment by Espebaum** [comment]
헉!!!

**Comment by Espebaum** [comment]
통과했습니다
<img width="2548" alt="image" src="https://github.com/soulee-dev/webserv/assets/104741009/f5a854f8-6ed8-4c2a-9fe6-b67292bee4aa">

Test POST http://localhost:80/post_body with a size of 0
FATAL ERROR ON LAST TEST: bad status code 
이제이거보면될것같습니다.

**Comment by CodyKat** [comment]
오 어떻게 해결하셨나요?

**Comment by Espebaum** [comment]
마스터로 하시면 될것같습니다!!

**Comment by soulee-dev** [comment]
#102 구현 완료
